<h1>越简单，越美好！<small>More simpler more better</small></h1>
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"				
			data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span> 
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">首页</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse"
			id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li class="<?= $nav==2?"active":""?>"><a href="/tag/cakephp.html">Cakephp</a></li>
				<li class="<?= $nav==3?"active":""?>"><a href="/link.html">友情链接</a></li>
				<li class="dropdown <?= $nav==4?"active":""?>"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown" role="button" aria-haspopup="true"
					aria-expanded="false">标签 <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<?php foreach ($hotTags as $tag){?>
						<li><a href="/tag/<?= $tag->tagTitle?>.html"><?= $tag->tagTitle?></a></li>
						<?php }?>
						<li role="separator" class="divider"></li>
						<li><a href="/tags.html">所有标签</a></li>
					</ul></li>
			</ul>
			<!-- <form class="navbar-form navbar-left" method="get" action="/search.html">
				<div class="form-group">
					<input type="text" class="form-control" name="key" required="required" placeholder="Search">
				</div>
				 <button type="submit" class="btn btn-default">搜索</button>
			</form> -->
		</div>
	</div>
</nav>